services:
  - type: web
    name: iwsreports
    runtime: docker
    buildCommand: docker build -t iwsreports .
    startCommand: docker run iwsreports
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"