services:
  - type: web
    name: iwsreports
    runtime: native
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Távolítsuk el a PUPPETEER_EXECUTABLE_PATH és PUPPETEER_SKIP_CHROMIUM_DOWNLOAD beállításokat