services:
  - type: web
    name: iwsreports
    runtime: docker
    build:
      dockerfile: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      # Töröld vagy kommenteld ki a PUPPETEER változókat
      # - key: PUPPETEER_EXECUTABLE_PATH
      #   value: /usr/bin/google-chrome-stable
      # - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
      #   value: true