services:
  - type: web
    name: iwsreports
    runtime: docker
    build:
      dockerfile: Dockerfile
    routes:
      - type: path
        path: /*
    envVars:
      - key: NODE_ENV
        value: production