
services:
  - type: web
    name: iwsreports
    runtime: docker
    build:
      dockerfile: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome