services:
  - type: web
    name: iwsreports
    runtime: docker
    plan: starter # Change this according to your needs
    build:
      dockerfile: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true" # Make sure this is a string "true" not boolean